# Generated by Django 5.0.7 on 2024-09-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_rename_service_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic_url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
