# Generated by Django 5.0.7 on 2024-10-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_style_images_userprofile_profile_pic_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
